// Industrial Colonies - Fan Fluid Processing
//
// KJSGen exports Fan Fluid Processing recipes into this registry instead of
// ordinary furnace/blasting recipes. This prevents custom fan-only recipes from
// silently becoming valid in vanilla furnaces.
//
// The Java/Create fan-processing bridge will consume these definitions once the
// dedicated FanProcessingType backend is installed.

global.IndustrialFanProcessing = global.IndustrialFanProcessing || {
  definitions: [],

  register(definition) {
    if (!definition || !definition.fan || !definition.input || !definition.fluid || !definition.outputs) {
      console.error('[Industrial Colonies] Invalid Fan Fluid Processing definition: ' + JSON.stringify(definition))
      return
    }

    const processingType = String(definition.processingType || 'fluid').toLowerCase()
    const validProcessingTypes = ['fluid', 'heat']

    if (!validProcessingTypes.includes(processingType)) {
      console.error('[Industrial Colonies] Invalid fan processing type "' + processingType + '".')
      return
    }

    definition.processingType = processingType
    definition.consumeFluid = definition.consumeFluid === true

    // Heat-processing recipes are intended to use fluids in
    // #industrial_colonies:fan_hot_fluids. The KJSGen fluid browser currently
    // cannot filter its search results by an arbitrary tag, so the editor still
    // permits any fluid to be selected. The backend bridge should enforce this
    // tag when processingType === 'heat'.
    definition.hotFluidTag = processingType === 'heat'
      ? 'industrial_colonies:fan_hot_fluids'
      : null

    this.definitions.push(definition)
  }
}

ServerEvents.recipes(event => {
  // Recipes generated by KJSGen call global.IndustrialFanProcessing.register(...)
  // inside this event. No vanilla smelting/blasting recipe is created here.
})

ServerEvents.loaded(event => {
  const count = global.IndustrialFanProcessing.definitions.length
  if (count > 0) {
    console.info('[Industrial Colonies] Loaded ' + count + ' Fan Fluid Processing definition(s).')
  }
})
