// Industrial Colonies - Fan Fluid Processing
//
// KJSGen exports Fan Fluid Processing recipes into this registry instead of
// ordinary furnace/blasting recipes. This prevents custom fan-only recipes from
// silently becoming valid in vanilla furnaces.
//
// The Java/Create fan-processing bridge will consume these definitions once the
// dedicated FanProcessingType backend is installed.

global.IndustrialFanProcessing = global.IndustrialFanProcessing || {
  definitions: [],

  register(definition) {
    if (!definition || !definition.input || !definition.fluid || !definition.outputs) {
      console.error('[Industrial Colonies] Invalid Fan Fluid Processing definition: ' + JSON.stringify(definition))
      return
    }

    const mode = String(definition.mode || 'heat').toLowerCase()
    const validModes = ['heat', 'wash', 'cool', 'reactive']

    if (!validModes.includes(mode)) {
      console.error('[Industrial Colonies] Invalid Fan Fluid Processing mode "' + mode + '".')
      return
    }

    definition.mode = mode
    definition.consumeFluid = definition.consumeFluid === true
    this.definitions.push(definition)
  }
}

ServerEvents.recipes(event => {
  // Recipes generated by KJSGen call global.IndustrialFanProcessing.register(...)
  // inside this event. No vanilla smelting/blasting recipe is created here.
})

ServerEvents.loaded(event => {
  const count = global.IndustrialFanProcessing.definitions.length
  if (count > 0) {
    console.info('[Industrial Colonies] Loaded ' + count + ' Fan Fluid Processing definition(s).')
  }
})
