// kjsgen:start TEST
// Generated by KubeJS Generator (kjsgen) from project 'TEST'.
// Everything inside this marker block is overwritten on re-export; edits outside it are kept.
ServerEvents.recipes(event => {
  if (Platform.isLoaded('create')) {
    // advanced_ae:quantum_processor
    event.recipes.create.sequenced_assembly(['advanced_ae:quantum_processor'], 'create:refined_radiance_casing', [
        event.recipes.industrial_colonies.base_deploying('ae2:printed_logic_processor', ['ae2:printed_logic_processor', 'tfmg:steel_frame']),
        event.recipes.industrial_colonies.base_pressing('ae2:printed_logic_processor', 'ae2:printed_logic_processor')
      ]).transitionalItem('ae2:printed_logic_processor').loops(1)
  }
})
// kjsgen:end TEST
