#If boss health should be scaled
"Should Scale Boss Health" = true
#If boss drops should be rolled an additional time per player
"Should Scale Boss Drops" = true
#The amount to scale boss health per player after the first
# Default: 1.0
# Range: 0.0 ~ 1.7976931348623157E308
"Health Multiplier Per Player" = 1.0
#A flat value to increase boss health. Will override "Health Multiplier Per Player" if it is not 0
# Default: 0.0
# Range: 0.0 ~ 1.7976931348623157E308
"Flat Health Multiplier" = 0.0
#A flat value to increase boss. If this value is not 0 player count will be ignored
# Default: 0
# Range: > 0
"Flat Drop Multiplier" = 0
#Whether to use the tags in your modloader (Forge, Neoforge, Fabric) to detect bosses. Will still use Boss Names as a fallback
"Should Use Loader Tags" = true
#Whether to drop loot bags filled with boss items or just drop the plain items
"Should Drop Loot Bags" = true
#Whether to scale health and loot off of the number of players in the configured range or use the global player count
"Use Proximity Scaling" = true
#How far from a boss spawn position to detect players. Detects in a cube centered on the entity with each side being the configured number of blocks away.
# Default: 100
# Range: > 0
"Proximity Scaling Range" = 100
#All bosses that should be affected by this mod. Most are usually in the modloader (Forge, Neoforge, Fabric) tag
"Boss Entities" = ["minecraft:wither", "minecraft:ender_dragon", "cataclysm:ancient_remnant", "cataclysm:ignis", "cataclysm:maledictus", "cataclysm:ender_golem", "cataclysm:ender_guardian", "cataclysm:the_leviathan", "cataclysm:the_harbinger", "cataclysm:netherite_monstrosity", "bosses_of_mass_destruction:void_blossom", "bosses_of_mass_destruction:gauntlet", "bosses_of_mass_destruction:lich", "bosses_of_mass_destruction:obsidilith"]
