[entries]
	actuator = true
	advanced_barrel = true
	advanced_lithium_ion_battery = true
	advanced_processor = true
	advanced_storage_container = true
	advanced_voltaic_pile = true
	alloy_smelter = true
	americium_rtg = true
	analyzer = true
	assembler = true
	basic_barrel = true
	basic_electric_circuit = true
	basic_electromagnet = true
	basic_electromagnet_slope = true
	basic_lithium_ion_battery = true
	basic_processor = true
	basic_rf_amplifier = true
	basic_storage_container = true
	basic_voltaic_pile = true
	bioplastic = true
	black_hole = true
	bscco_electromagnet = true
	bscco_electromagnet_slope = true
	bscco_rf_amplifier = true
	californium_rtg = true
	centrifuge = true
	chamber_port = true
	chamber_terminal = true
	charging_station = true
	chassis = true
	chemical_reactor = true
	coil_bscco = true
	coil_copper = true
	coil_magnesium_diboride = true
	compact_helium_collector = true
	compact_nitrogen_collector = true
	compact_water_collector = true
	compression_charge = true
	crafting_pattern = true
	crystallizer = true
	decay_generator = true
	decay_hastener = true
	dense_helium_collector = true
	dense_nitrogen_collector = true
	dense_water_collector = true
	du_barrel = true
	du_lithium_ion_battery = true
	du_storage_container = true
	du_voltaic_pile = true
	dummy_turbine_blade = true
	electrolyzer = true
	elite_barrel = true
	elite_lithium_ion_battery = true
	elite_processor = true
	elite_storage_container = true
	elite_voltaic_pile = true
	empty_frame = true
	empty_sink = true
	end_of_the_world = true
	energy_upgrade = true
	engineers_crafting_table = true
	event_horizon_stabilizer = true
	expl = true
	expl_proxy = true
	extractor = true
	feral_ghoul_spawn_egg = true
	fission_reactor_casing = true
	fission_reactor_controller = true
	fission_reactor_designer = true
	fission_reactor_glass = true
	fission_reactor_irradiation_chamber = true
	fission_reactor_pile-driver_irradiation_chamber = true
	fission_reactor_plan = true
	fission_reactor_port = true
	fission_reactor_solid_fuel_cell = true
	fluid_enricher = true
	fluid_infuser = true
	fuel_reprocessor = true
	fusion_reactor_casing = true
	fusion_reactor_connector = true
	fusion_reactor_core = true
	fusion_reactor_core_proxy = true
	fusion_reactor_glass = true
	gas_scrubber = true
	glowing_mushroom = true
	heat_exchanger = true
	heat_exchanger_casing = true
	heat_exchanger_cold_coolant_port = true
	heat_exchanger_controller = true
	heat_exchanger_hot_coolant_port = true
	heat_exchanger_radiator = true
	helium_collector = true
	hev_armor = true
	hyperspace = true
	ingot_former = true
	irradiator = true
	isotope_separator = true
	lava_collector = true
	leacher = true
	lithium_ion_cell = true
	magnesium_diboride_electromagnet = true
	magnesium_diboride_electromagnet_slope = true
	magnesium_diboride_rf_amplifier = true
	manufactory = true
	melter = true
	money_for_nothing = true
	motor = true
	msr_controller = true
	msr_fuel_cell = true
	msr_port = true
	multiblock_builder = true
	multitool = true
	nc_ore_veins = true
	neutron_initiator = true
	neutronium_frame = true
	niobium_tin_electromagnet = true
	niobium_tin_electromagnet_slope = true
	niobium_tin_rf_amplifier = true
	niobium_titanium_electromagnet = true
	niobium_titanium_electromagnet_slope = true
	niobium_titanium_rf_amplifier = true
	nitrogen_collector = true
	nuclear_furnace = true
	photon_concentrator = true
	pipe = true
	pipe_connector = true
	plate_advanced = true
	plate_basic = true
	plate_du = true
	plate_elite = true
	plate_extreme = true
	plutonium_rtg = true
	pressurizer = true
	pu_239_bomb = true
	pu_239_core = true
	pu_239_pit = true
	pump = true
	q36_quantite_disruptor = true
	qnp = true
	quantum_flux_regulator = true
	quantum_transformer = true
	quantum_upgrade = true
	research_paper = true
	resonite_crystal = true
	resonite_shard = true
	rock_crusher = true
	servo = true
	sic_fiber = true
	silicon_boule = true
	silicon_n_doped = true
	silicon_p_doped = true
	silicon_wafer = true
	solar_panel_advanced = true
	solar_panel_basic = true
	solar_panel_du = true
	solar_panel_elite = true
	spaxelhoe_thorium = true
	spaxelhoe_tough = true
	speed_upgrade = true
	stack_upgrade = true
	steam_turbine = true
	steel_frame = true
	subatomic_liquifier = true
	supercooler = true
	tough_armor = true
	turbine_aluminum_coil = true
	turbine_basic_rotor_blade = true
	turbine_bearing = true
	turbine_beryllium_coil = true
	turbine_casing = true
	turbine_controller = true
	turbine_copper_coil = true
	turbine_extreme_rotor_blade = true
	turbine_glass = true
	turbine_gold_coil = true
	turbine_magnesium_coil = true
	turbine_port = true
	turbine_rotor_shaft = true
	turbine_sic_sic_cmc_rotor_blade = true
	turbine_silver_coil = true
	turbine_steel_rotor_blade = true
	uranium_rtg = true
	wanderer = true
	wasteland_earth = true
	wasteland_portal = true
	water_collector = true
