[q36_quantite_disruptor]
	# Default: 10
	# Range: 1 ~ 1200
	pulse_cooldown_ticks = 10
	# Default: 200
	# Range: > 0
	pulse_qc_cost = 200
	# Default: 50.0
	# Range: 0.0 ~ 100000.0
	pulse_damage = 50.0
	# Default: 200000
	# Range: 0 ~ 9223372036854775807
	pulse_radiation = 200000
	# Default: 10
	# Range: 0 ~ 200
	pulse_fx_ticks = 10
	# Default: 60
	# Range: 1 ~ 1200
	beam_cooldown_ticks = 60
	# Default: 2000
	# Range: > 0
	beam_qc_cost = 2000
	# Default: 200.0
	# Range: 0.0 ~ 100000.0
	beam_damage = 200.0
	# Default: 2000000
	# Range: 0 ~ 9223372036854775807
	beam_radiation = 2000000
	# Default: 64.0
	# Range: 1.0 ~ 512.0
	beam_range = 64.0
	# Default: 2
	# Range: 0 ~ 16
	beam_block_break_radius = 2
	# Default: 10
	# Range: 0 ~ 200
	beam_fx_ticks = 10
